server:
  forward-headers-strategy: native
  # https://www.baeldung.com/spring-boot-custom-error-page
  # https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-error-handling-custom-error-pages
  error:
    whitelabel:
      enabled: false
    path: /error
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1KB
  shutdown: graceful

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/animus
    username: ${MYSQL_USER:jung}
    password: ${MYSQL_PASSWORD:secret}
    pool:
      validation-query: SELECT 1
      max-idle-time: 30m
    properties:
      sslMode: DISABLE
      schema: main
